apiVersion: v1
kind: ServiceAccount
metadata:
  name: trident-api
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: trident-api
  namespace: default
rules:
  - apiGroups: ["trident.dev"]
    resources: ["pipelineruns"]
    verbs: ["get", "list", "create"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: trident-api
  namespace: default
subjects:
  - kind: ServiceAccount
    name: trident-api
    namespace: default
roleRef:
  kind: Role
  name: trident-api
  apiGroup: rbac.authorization.k8s.io
